In [1]:
#import library
import numpy as np

In [2]:
# sigmoid function to normalize inputs
# sigmoid f(x) = 1/1+e^-x
def sigmoid(x) : 
    return 1 / (1 + np.exp(-x))

In [3]:
# sigmoid derivatives to adjust synaptics weight
def sigmoid_derivative(x) :
    return x * (1 - x)

In [4]:
#input dataset 
training_inputs = np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1],])

In [5]:
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [6]:
# output dataset
training_outputs = np.array([[0,1,1,0]]).T
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [7]:
# seed random numbers to make calculations 
# seed the random number generator,so it's generates same numbers
# every time the program runs
np.random.seed(1)

In [8]:
# initialize weight randomely with mean 0 to create matrix,synaptic weight
# we model a single neuron , with 3 input connection and 1 output connection.
# we assign random weights to a 3x1 matrix with values in the range from 1 to -1.
# and mean 0
synaptic_weights = 2*np.random.random((3,1))-1

In [9]:
print('Random starting synaptic weights :')
print(synaptic_weights)

Random starting synaptic weights :
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [10]:
# Iterate 10,000 times
for iteration in range(10000) :
    # define input layer
    input_layer = training_inputs
    # Normalize the product of the input
    outputs = sigmoid(np.dot(input_layer,synaptic_weights)) 
    # how much did we miss?
    error = training_outputs - outputs
    # multiply how much we missed by the
    # slope of the sigmoid at the values in outputs
    adjustments = error * sigmoid_derivative(outputs)
    # update weights
    synaptic_weights += np.dot(input_layer.T,adjustments) 

In [11]:
print('Synaptic weights after training : ')
print(synaptic_weights)

Synaptic weights after training : 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [12]:
print('Output after training : ')
print(outputs)

Output after training : 
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]
