In [1]:
# import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
weight = ['sunny','sunny','covercast','rainy','rainy','rainy','covercast','sunny','sunny','rainy','sunny','overcast','overcast','rainy']

In [3]:
weight

['sunny',
 'sunny',
 'covercast',
 'rainy',
 'rainy',
 'rainy',
 'covercast',
 'sunny',
 'sunny',
 'rainy',
 'sunny',
 'overcast',
 'overcast',
 'rainy']

In [4]:
temp = ['hot','hot','hot','mild','cool','cool','cool','mild','cool','mild','mild','mild','hot','mild']

In [5]:
temp

['hot',
 'hot',
 'hot',
 'mild',
 'cool',
 'cool',
 'cool',
 'mild',
 'cool',
 'mild',
 'mild',
 'mild',
 'hot',
 'mild']

In [6]:
play = ['no','no','yes','yes','yes','no','yes','no','yes','yes','yes','yes','yes','no']

In [7]:
play

['no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no']

In [8]:
from sklearn import preprocessing

In [9]:
le = preprocessing.LabelEncoder()

In [10]:
weather_encoded = le.fit_transform(weight)

In [11]:
weather_encoded

array([3, 3, 0, 2, 2, 2, 0, 3, 3, 2, 3, 1, 1, 2], dtype=int64)

In [12]:
label_col = le.fit_transform(play)

In [13]:
label_col

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [14]:
temp_encoded = le.fit_transform(temp)

In [15]:
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [16]:
features_zip = list(zip(weather_encoded,temp_encoded))

In [17]:
features_zip

[(3, 1),
 (3, 1),
 (0, 1),
 (2, 2),
 (2, 0),
 (2, 0),
 (0, 0),
 (3, 2),
 (3, 0),
 (2, 2),
 (3, 2),
 (1, 2),
 (1, 1),
 (2, 2)]

# KNN : K-Nearest Neighbors

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
model = KNeighborsClassifier(n_neighbors = 3)

In [20]:
model.fit(features_zip,label_col)

KNeighborsClassifier(n_neighbors=3)

In [21]:
predicted = model.predict([[0,0]])
print(predicted)

[1]
